apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-solver
  namespace: sudoku-solver
  labels:
    app: sudoku-solver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sudoku-solver
  template:
    metadata:
      labels:
        app: sudoku-solver
    spec:
      containers:
      - name: sudoku-solver
        image: maxbergmark/sudoku-solver
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: sudoku-solver
  namespace: sudoku-solver
spec:
  selector:
    app: sudoku-solver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
